name: documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: ./docs/docs_environment.yml
          activate-environment: sphinx_env
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: generate version info
        shell: bash -l {0}
        run: python setup.py --version

      - name: Build docs
        shell: bash -l {0}
        run: sphinx-build -W -n -b html -d docs/_build/doctrees docs docs/_build/html --keep-going

      - uses: actions/upload-artifact@v1
        with:
          name: schema-docs
          path: docs/_build/html
