name: pytest
on: [push]

jobs:
  pytest:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        py: [ '3.7', '3.8' , '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: pip installs
        run: |
          pip install ".[test]"
      - name: run pytest
        run: |
          pytest
