id: http://{{ cookiecutter.organization_name }}/weldx/standards/manifests/{{ cookiecutter.project_slug}}-1.0.0
extension_uri: http://{{ cookiecutter.organization_name }}/weldx/standards/{{ cookiecutter.project_slug}}-1.0.0
title: {{cookiecutter.project_name}}
description: |-
  {{ cookiecutter.description }}
asdf_standard_requirement: 1.0.0
tags:
  - uri: "asdf://weldx.bam.de/weldx/schemas/equipment/measurement_equipment-0.1.0"
    file: "measurement_equipment_example_schema-1.0.0"
